### ISSUE TITLE
Handles only a subset of the possible code paths

### ISSUE THREAD

**Issue by dscho** [matheustavares/callpath#11]
Whenever you use `gdb` to analyze anything, you only get the code paths that are hit by that particular run of the program.

In https://github.com/dscho/gen-callgraph.ts (very much underdocumented, and also my first baby steps in Typescript, sorry), I tried to use the disassembly instead: analyzing the machine code, function by function, adding a new callee whenever there is a jump to a symbol that refers to one of "our" functions.

Maybe that would be a better approach for you, too?

**Comment by matheustavares** [comment]
First of all, sorry for the late reply, @dscho . I somehow missed this issue...

Thanks for sharing `gen-callgraph.ts`! When I prototyped `callpath`, I was interested only in the paths taken during an specific execution. But it would be very nice for this script to have an option for static analysis as well. @giulianobelinassi suggested me to use a gcc's LTO feature for that (#3 ). And there's also cflow. But reading the binary would be very interesting as it could exclude some conditional compiled snippets. Again, thanks for sharing it.
