### ISSUE TITLE
Use LTO infrastructure to retrieve all paths

### ISSUE THREAD

**Issue by giulianobelinassi** [matheustavares/callpath#3]
GCC has a Link Time Optimization feature that allows the entire program to be analyzed. The program callgraph can be retrieved from there.

A patch for dumping the callgraph has already been submitted to GCC: https://gcc.gnu.org/ml/gcc-patches/2019-06/msg01892.html

**Comment by matheustavares** [comment]
Nice! It could be done as a `--static` option. This way we could have both dynamic and static analysis. We may even include a `cflow` parser for that.

**Comment by matheustavares** [comment]
Thanks a lot for the help, Giuliano. I decided to aim this project on dynamic analysis only, whereas [gcc-callgraph-plugin](https://github.com/matheustavares/gcc-callgraph-plugin) will take care of static analysis. So I'll close this issue.

(Thanks for helping me with the gcc-plugin :)
